language: python
python:
    - "2.7"

install: 
    - pip install coveralls
    - python setup.py install

script: 
    - coverage run --source=django_record setup.py test

after_success:
    coveralls
